# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f85e75370e43d5f94fb93afc02334ec38682fcd0ed9774ec429cb648dc6885652298e248a7cdc91757b95f6c9fba5dce57bd891fd16c05544f15dea0acfc5aa4

test:
  secret_key_base: b9d0f9f74bdf95782b088bc32aafd7fef825e0e030521ad5f60b27a3fa3820b87bc45a6732d853bdc155a4d2f7f5e0df1d7744499c48e00f8ad920a85916014a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
